const Users = {
    GET_USER_DATA:'GET_USER_DATA',
    CREATE_USER_ACCOUNT:'CREATE_USER_ACCOUNT',
    LOGIN_USER:'LOGIN_USER',
    FORGOT_PASSWORD:'FORGOT_PASSWORD',
    CHANGE_PASSWORD:'CHANGE_PASSWORD',
}
export default Users;
